<?php
declare(strict_types=1);
require dirname(__DIR__) . '/vendor/autoload.php';
use App\Core\Database;
use App\Services\{ProjectDomainService, ProjectService, LogService};

function ensure(bool $ok, string $message): void { if (!$ok) throw new RuntimeException($message); }
function rejected(callable $call): void { try { $call(); } catch (Throwable) { return; } throw new RuntimeException('Expected rejection'); }
$dir = sys_get_temp_dir() . '/tmpbase-domains-' . bin2hex(random_bytes(5));
mkdir($dir . '/projects', 0775, true);
$config = ['storage' => $dir, 'database' => $dir . '/central.sqlite', 'url' => 'https://api.example.com', 'domains' => ['ips' => ['203.0.113.10'], 'reserved' => ['realtime.example.com']]];
$db = Database::connect($config['database']);
Database::migrate($db);
ProjectDomainService::migrate($db);
ProjectDomainService::migrate($db);
$projects = new ProjectService($db, $config, new LogService($db));
$p = $projects->create(['name' => 'Domain One']);
$p2 = $projects->create(['name' => 'Domain Two']);
$records = [];
$domains = new ProjectDomainService($db, $config, static function ($host, $type) use (&$records) { return $records[$host][$type] ?? []; });
foreach (['https://shop.com','shop.com/a','*.shop.com','shop.com:443','127.0.0.1','shop.com`','-bad.com','shop..com'] as $bad) rejected(fn () => ProjectDomainService::hostname($bad));
ensure(ProjectDomainService::hostname(' SHOP.COM. ') === 'shop.com', 'Domain normalization');
rejected(fn () => $domains->save($p['uid'], 'api.example.com', null));
$domains->save($p['uid'], 'shop.example.com', 'sistema.shop.example.com');
$rows = array_column($domains->all($p['uid']), null, 'destination');
$id = (int) $rows['store']['id'];
rejected(fn () => $domains->save($p2['uid'], 'other.example.com', 'sistema.shop.example.com'));
ensure($domains->all($p2['uid']) === [], 'Pair save must roll back on duplicate');
rejected(fn () => $domains->verify($p2['uid'], $id));
rejected(fn () => $domains->verify($p['uid'], $id));
$records['_tmpbase.shop.example.com'][DNS_TXT] = [['txt' => 'tmpbase=' . $rows['store']['verification_token']]];
$type = DNS_A | DNS_AAAA | DNS_CNAME;
$records['shop.example.com'][$type] = [['ip' => '203.0.113.11']];
rejected(fn () => $domains->verify($p['uid'], $id));
$records['shop.example.com'][$type] = [['ip' => '203.0.113.10'], ['ipv6' => '2001:db8::5']];
rejected(fn () => $domains->verify($p['uid'], $id));
$records['shop.example.com'][$type] = [['target' => 'origin.example.com']];
$records['origin.example.com'][$type] = [['ip' => '203.0.113.10']];
$domains->verify($p['uid'], $id);
$resolved = $domains->resolve('shop.example.com');
ensure($resolved['status'] === 'active', 'DNS activation');
ensure(ProjectDomainService::allowedPath($resolved, '/'), 'Store root');
ensure(ProjectDomainService::allowedPath($resolved, '/store/domain-one/cart'), 'Cart');
ensure(ProjectDomainService::allowedPath($resolved, '/api/storefront/domain-one/checkout'), 'Checkout');
foreach (['/dashboard','/projects/' . $p['uid'], '/store/domain-two', '/store/domain-one-other', '/sistema/domain-one', '/api/system/domain-two/runtime'] as $path) ensure(!ProjectDomainService::allowedPath($resolved, $path), 'Tenant isolation: ' . $path);
$domains->save($p['uid'], 'shop.example.com', null);
ensure($domains->resolve('shop.example.com')['status'] === 'active', 'Unchanged save preserves activation');
$domains->disable($p['uid'], $id);
ensure(!ProjectDomainService::allowedPath($domains->resolve('shop.example.com'), '/'), 'Disabled route');
$domains->verify($p['uid'], $id);
$projects->block($p['uid'], 'Test');
ensure(!ProjectDomainService::allowedPath($domains->resolve('shop.example.com'), '/'), 'Blocked project');
$domains->save($p['uid'], 'new.example.com', null);
ensure($domains->resolve('shop.example.com') === null, 'Old host removed');
ensure($domains->resolve('new.example.com')['status'] === 'pending', 'Changed hostname requires proof');
ensure($domains->resolve('new.example.com')['verification_token'] !== $rows['store']['verification_token'], 'Proof rotates');
$domains->remove($p['uid'], $id);
ensure($domains->resolve('new.example.com') === null, 'Unlink');
echo "PASS: domain validation, atomic save, DNS ownership, IPv4/IPv6/CNAME, tenant isolation, blocked projects and lifecycle\n";
