<?php use App\Core\Csrf; ?>
<div class="mb-6"><h2 class="text-xl font-bold text-white">API Documentation</h2><p class="mt-1 text-sm text-slate-500">RESTful JSON API for your projects.</p></div>

<section class="mb-8 space-y-6">
<article class="card p-5"><h3 class="font-semibold text-white">Authentication</h3><p class="mt-2 text-sm text-slate-400">Include a Bearer token in the <code class="rounded bg-black/30 px-1.5 py-0.5 text-xs text-brand">Authorization</code> header.</p>
<div class="mt-4 overflow-auto rounded-xl bg-black/30 p-4 text-xs text-slate-300"><pre>Authorization: Bearer YOUR_API_KEY</pre></div>
<p class="mt-3 text-sm text-slate-400">Use the <strong class="text-slate-200">Public key</strong> for read-only access to public/private tables. Use the <strong class="text-slate-200">Secret key</strong> for write access. Find your keys in the project settings.</p></article>

<article class="card p-5"><h3 class="font-semibold text-white">Base URL</h3>
<div class="mt-4 overflow-auto rounded-xl bg-black/30 p-4 text-xs text-slate-300"><pre><?= e($baseUrl) ?>/api/{project_uid}</pre></div></article>

<article class="card p-5"><h3 class="font-semibold text-white">Endpoints</h3><div class="mt-4 space-y-4">
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">POST</span><code class="text-xs text-slate-300">/api/project/create</code><span class="text-xs text-slate-500">Create a project with 7-day trial license (no auth)</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X POST "<?= e($baseUrl) ?>/api/project/create" \<br>  -H "Content-Type: application/json" \<br>  -d '{"name":"MyCompany","system_name":"SistemaFacturacion"}'</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">GET</span><code class="text-xs text-slate-300">/api/{project}/health</code><span class="text-xs text-slate-500">Server health &amp; table count</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl "<?= e($baseUrl) ?>/api/{project}/health" \<br>  -H "Authorization: Bearer YOUR_PUBLIC_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-rose-500/15 px-2 py-0.5 text-xs font-bold text-rose-400">DELETE</span><code class="text-xs text-slate-300">/api/{project}</code><span class="text-xs text-slate-500">Delete project permanently (DB, files, backups)</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X DELETE "<?= e($baseUrl) ?>/api/{project}" \<br>  -H "Authorization: Bearer YOUR_SECRET_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-amber-500/15 px-2 py-0.5 text-xs font-bold text-amber-400">POST</span><code class="text-xs text-slate-300">/api/{project}/backups</code><span class="text-xs text-slate-500">Create a backup of the project database</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X POST "<?= e($baseUrl) ?>/api/{project}/backups" \<br>  -H "Authorization: Bearer YOUR_SECRET_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">GET</span><code class="text-xs text-slate-300">/api/{project}/backups</code><span class="text-xs text-slate-500">List all backups of the project</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl "<?= e($baseUrl) ?>/api/{project}/backups" \<br>  -H "Authorization: Bearer YOUR_PUBLIC_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">GET</span><code class="text-xs text-slate-300">/api/{project}/backups/{uid}/download</code><span class="text-xs text-slate-500">Download a backup file</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -O -J "<?= e($baseUrl) ?>/api/{project}/backups/bak_abc123/download" \<br>  -H "Authorization: Bearer YOUR_SECRET_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-amber-500/15 px-2 py-0.5 text-xs font-bold text-amber-400">POST</span><code class="text-xs text-slate-300">/api/{project}/backups/{uid}/restore</code><span class="text-xs text-slate-500">Restore a backup (creates safety backup first)</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X POST "<?= e($baseUrl) ?>/api/{project}/backups/bak_abc123/restore" \<br>  -H "Authorization: Bearer YOUR_SECRET_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-rose-500/15 px-2 py-0.5 text-xs font-bold text-rose-400">DELETE</span><code class="text-xs text-slate-300">/api/{project}/backups/{uid}</code><span class="text-xs text-slate-500">Delete a backup file</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X DELETE "<?= e($baseUrl) ?>/api/{project}/backups/bak_abc123" \<br>  -H "Authorization: Bearer YOUR_SECRET_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">GET</span><code class="text-xs text-slate-300">/api/{project}/schema</code><span class="text-xs text-slate-500">All tables with their columns and record count</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl "<?= e($baseUrl) ?>/api/{project}/schema" \<br>  -H "Authorization: Bearer YOUR_PUBLIC_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">GET</span><code class="text-xs text-slate-300">/api/{project}/schema/tables</code><span class="text-xs text-slate-500">List tables</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl "<?= e($baseUrl) ?>/api/{project}/schema/tables" \<br>  -H "Authorization: Bearer YOUR_PUBLIC_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">GET</span><code class="text-xs text-slate-300">/api/{project}/schema/tables/{table}</code><span class="text-xs text-slate-500">Columns of a single table</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl "<?= e($baseUrl) ?>/api/{project}/schema/tables/invoices" \<br>  -H "Authorization: Bearer YOUR_PUBLIC_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-blue-500/15 px-2 py-0.5 text-xs font-bold text-blue-400">GET</span><code class="text-xs text-slate-300">/api/{project}/{table}</code><span class="text-xs text-slate-500">List records (paginated)</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl "<?= e($baseUrl) ?>/api/{project}/invoices?page=1&amp;limit=10" \<br>  -H "Authorization: Bearer YOUR_PUBLIC_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">GET</span><code class="text-xs text-slate-300">/api/{project}/{table}/{uid}</code><span class="text-xs text-slate-500">Read a record</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl "<?= e($baseUrl) ?>/api/{project}/invoices/rec_abc123" \<br>  -H "Authorization: Bearer YOUR_PUBLIC_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-amber-500/15 px-2 py-0.5 text-xs font-bold text-amber-400">POST</span><code class="text-xs text-slate-300">/api/{project}/{table}</code><span class="text-xs text-slate-500">Create a record</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X POST "<?= e($baseUrl) ?>/api/{project}/invoices" \<br>  -H "Authorization: Bearer YOUR_SECRET_KEY" \<br>  -H "Content-Type: application/json" \<br>  -d '{"name":"Example","value":42}'</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-orange-500/15 px-2 py-0.5 text-xs font-bold text-orange-400">PUT</span><code class="text-xs text-slate-300">/api/{project}/{table}/{uid}</code><span class="text-xs text-slate-500">Update a record</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X PUT "<?= e($baseUrl) ?>/api/{project}/invoices/rec_abc123" \<br>  -H "Authorization: Bearer YOUR_SECRET_KEY" \<br>  -H "Content-Type: application/json" \<br>  -d '{"value":99}'</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-rose-500/15 px-2 py-0.5 text-xs font-bold text-rose-400">DELETE</span><code class="text-xs text-slate-300">/api/{project}/{table}/{uid}</code><span class="text-xs text-slate-500">Delete a record</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X DELETE "<?= e($baseUrl) ?>/api/{project}/invoices/rec_abc123" \<br>  -H "Authorization: Bearer YOUR_SECRET_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-amber-500/15 px-2 py-0.5 text-xs font-bold text-amber-400">POST</span><code class="text-xs text-slate-300">/api/{project}/{table}/bulk</code><span class="text-xs text-slate-500">Bulk insert (up to 1000 rows)</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X POST "<?= e($baseUrl) ?>/api/{project}/invoices/bulk" \<br>  -H "Authorization: Bearer YOUR_SECRET_KEY" \<br>  -H "Content-Type: application/json" \<br>  -d '[{"name":"A"},{"name":"B"}]'</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-amber-500/15 px-2 py-0.5 text-xs font-bold text-amber-400">POST</span><code class="text-xs text-slate-300">/api/{project}/{table}/upsert</code><span class="text-xs text-slate-500">Insert or update by uid</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X POST "<?= e($baseUrl) ?>/api/{project}/invoices/upsert" \<br>  -H "Authorization: Bearer YOUR_SECRET_KEY" \<br>  -H "Content-Type: application/json" \<br>  -d '{"uid":"rec_abc123","name":"Updated"}'</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">GET</span><code class="text-xs text-slate-300">/api/{project}/sync?since=</code><span class="text-xs text-slate-500">Full project sync (changes across all tables + deletes)</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl "<?= e($baseUrl) ?>/api/{project}/sync?since=2026-06-01 00:00:00" \<br>  -H "Authorization: Bearer YOUR_PUBLIC_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">GET</span><code class="text-xs text-slate-300">/api/{project}/{table}/sync?from=&amp;to=</code><span class="text-xs text-slate-500">Get records modified in date range (single table)</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl "<?= e($baseUrl) ?>/api/{project}/invoices/sync?from=2026-06-01 00:00:00" \<br>  -H "Authorization: Bearer YOUR_PUBLIC_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">GET</span><code class="text-xs text-slate-300">/api/{project}/{table}/export?format=json|csv</code><span class="text-xs text-slate-500">Export all records</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl "<?= e($baseUrl) ?>/api/{project}/invoices/export?format=csv" \<br>  -H "Authorization: Bearer YOUR_PUBLIC_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-rose-500/15 px-2 py-0.5 text-xs font-bold text-rose-400">DELETE</span><code class="text-xs text-slate-300">/api/{project}/{table}</code><span class="text-xs text-slate-500">Truncate table (delete all records)</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X DELETE "<?= e($baseUrl) ?>/api/{project}/invoices" \<br>  -H "Authorization: Bearer YOUR_SECRET_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-amber-500/15 px-2 py-0.5 text-xs font-bold text-amber-400">POST</span><code class="text-xs text-slate-300">/api/{project}/storage/upload?directory=</code><span class="text-xs text-slate-500">Upload file to a directory (multipart/form-data)</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X POST "<?= e($baseUrl) ?>/api/{project}/storage/upload" \<br>  -H "Authorization: Bearer YOUR_SECRET_KEY" \<br>  -F "file=@logo.png" \<br>  -F "directory=company/logo"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">GET</span><code class="text-xs text-slate-300">/api/{project}/storage/files?directory=</code><span class="text-xs text-slate-500">List files in a directory</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl "<?= e($baseUrl) ?>/api/{project}/storage/files?directory=products" \<br>  -H "Authorization: Bearer YOUR_PUBLIC_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">GET</span><code class="text-xs text-slate-300">/api/{project}/storage/{uid}</code><span class="text-xs text-slate-500">Download/serve a file</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl "<?= e($baseUrl) ?>/api/{project}/storage/fil_abc123" \<br>  -H "Authorization: Bearer YOUR_PUBLIC_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-rose-500/15 px-2 py-0.5 text-xs font-bold text-rose-400">DELETE</span><code class="text-xs text-slate-300">/api/{project}/storage/{uid}</code><span class="text-xs text-slate-500">Delete a file</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X DELETE "<?= e($baseUrl) ?>/api/{project}/storage/fil_abc123" \<br>  -H "Authorization: Bearer YOUR_SECRET_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-amber-500/15 px-2 py-0.5 text-xs font-bold text-amber-400">POST</span><code class="text-xs text-slate-300">/api/{project}/licenses</code><span class="text-xs text-slate-500">Create license (secret key required)</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X POST "<?= e($baseUrl) ?>/api/{project}/licenses" \<br>  -H "Authorization: Bearer YOUR_SECRET_KEY" \<br>  -H "Content-Type: application/json" \<br>  -d '{"system_name":"MyApp","max_uses":100}'</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">GET</span><code class="text-xs text-slate-300">/api/{project}/licenses</code><span class="text-xs text-slate-500">List licenses</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl "<?= e($baseUrl) ?>/api/{project}/licenses" \<br>  -H "Authorization: Bearer YOUR_PUBLIC_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">GET</span><code class="text-xs text-slate-300">/api/{project}/licenses/{uid}</code><span class="text-xs text-slate-500">License detail</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl "<?= e($baseUrl) ?>/api/{project}/licenses/lic_abc123" \<br>  -H "Authorization: Bearer YOUR_PUBLIC_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">GET</span><code class="text-xs text-slate-300">/api/{project}/licenses/{uid}/devices</code><span class="text-xs text-slate-500">List authorized devices of a license</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl "<?= e($baseUrl) ?>/api/{project}/licenses/lic_abc123/devices" \<br>  -H "Authorization: Bearer YOUR_PUBLIC_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-amber-500/15 px-2 py-0.5 text-xs font-bold text-amber-400">POST</span><code class="text-xs text-slate-300">/api/{project}/licenses/{uid}/authorize-device</code><span class="text-xs text-slate-500">Authorize a device (moves from unauthorized to allowed)</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X POST "<?= e($baseUrl) ?>/api/{project}/licenses/lic_abc123/authorize-device" \<br>  -H "Authorization: Bearer YOUR_SECRET_KEY" \<br>  -H "Content-Type: application/json" \<br>  -d '{"device_id":"TMPOS-E8A5-001B-9A83-CB58"}'</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-amber-500/15 px-2 py-0.5 text-xs font-bold text-amber-400">POST</span><code class="text-xs text-slate-300">/api/{project}/licenses/{uid}/status</code><span class="text-xs text-slate-500">Change status</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X POST "<?= e($baseUrl) ?>/api/{project}/licenses/lic_abc123/status" \<br>  -H "Authorization: Bearer YOUR_SECRET_KEY" \<br>  -H "Content-Type: application/json" \<br>  -d '{"status":"blocked"}'</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-rose-500/15 px-2 py-0.5 text-xs font-bold text-rose-400">DELETE</span><code class="text-xs text-slate-300">/api/{project}/licenses/{uid}</code><span class="text-xs text-slate-500">Delete license</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X DELETE "<?= e($baseUrl) ?>/api/{project}/licenses/lic_abc123" \<br>  -H "Authorization: Bearer YOUR_SECRET_KEY"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">POST</span><code class="text-xs text-slate-300">/api/license/validate</code><span class="text-xs text-slate-500">Validate license (public, no auth)</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X POST "<?= e($baseUrl) ?>/api/license/validate" \<br>  -H "Content-Type: application/json" \<br>  -d '{"license_key":"A3F8C-D1E2B-4A61C","system_name":"MyApp"}'</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">GET / POST</span><code class="text-xs text-slate-300">/api/license/info</code><span class="text-xs text-slate-500">Get full license data by key (public, no auth)</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl "<?= e($baseUrl) ?>/api/license/info?license_key=A3F8C-D1E2B-4A61C"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">GET / POST</span><code class="text-xs text-slate-300">/licenses/info</code><span class="text-xs text-slate-500">Same as above (alias sin /api/)</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl "<?= e($baseUrl) ?>/licenses/info?license_key=A3F8C-D1E2B-4A61C"</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">POST</span><code class="text-xs text-slate-300">/api/license/connect</code><span class="text-xs text-slate-500">Validate + register device (public, no auth)</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X POST "<?= e($baseUrl) ?>/api/license/connect" \<br>  -H "Content-Type: application/json" \<br>  -d '{"license_key":"A3F8C-D1E2B-4A61C","device_id":"TMPOS-E8A5-001B-9A83-CB58"}'</pre></div></div>
<div class="rounded-lg bg-black/20 p-3"><div class="flex items-center gap-3"><span class="shrink-0 rounded bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-400">POST</span><code class="text-xs text-slate-300">/api/license/use</code><span class="text-xs text-slate-500">Use license (public, no auth)</span></div><div class="mt-2 overflow-auto rounded-lg bg-black/40 p-3 text-xs text-slate-300"><pre>curl -X POST "<?= e($baseUrl) ?>/api/license/use" \<br>  -H "Content-Type: application/json" \<br>  -d '{"license_key":"A3F8C-D1E2B-4A61C"}'</pre></div></div>
</div></article>

<article class="card p-5"><h3 class="font-semibold text-white">Query parameters</h3>
