<?php ?>
<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex,nofollow"><title>Administración del comercio</title>
<style>
*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;grid-template-columns:1.1fr .9fr;background:#07111f;color:#e8eef8;font:15px/1.5 Inter,system-ui,sans-serif}.visual{position:relative;overflow:hidden;display:flex;flex-direction:column;justify-content:space-between;padding:54px;background:radial-gradient(circle at 20% 20%,#1d4ed866,transparent 36%),radial-gradient(circle at 80% 80%,#0f766e66,transparent 35%),#0a1628}.brand{display:flex;align-items:center;gap:12px;font-size:18px;font-weight:900}.mark{width:42px;height:42px;display:grid;place-items:center;border-radius:13px;background:#fff;color:#0f172a}.visual h1{max-width:720px;margin:0;font-size:clamp(42px,6vw,78px);line-height:.98;letter-spacing:-.06em}.visual p{max-width:620px;color:#aabbd2;font-size:18px}.features{display:flex;gap:9px;flex-wrap:wrap}.features span{border:1px solid #ffffff24;border-radius:999px;padding:8px 12px;color:#c9d6e8}.login{display:grid;place-items:center;padding:32px;background:#f4f7fb;color:#0f172a}.box{width:min(440px,100%);padding:40px;border:1px solid #dfe6ef;border-radius:24px;background:white;box-shadow:0 25px 80px #0f172a18}.box h2{font-size:30px;letter-spacing:-.035em;margin:0}.box>p{color:#64748b;margin:8px 0 28px}.field{display:block;margin-top:16px;font-size:12px;font-weight:900}.field input{width:100%;height:50px;margin-top:7px;border:1px solid #cbd5e1;border-radius:12px;padding:0 14px;font:inherit;outline:0}.field input:focus{border-color:#2563eb;box-shadow:0 0 0 4px #2563eb15}.submit{width:100%;height:52px;margin-top:22px;border:0;border-radius:12px;background:#0f172a;color:white;font-weight:900;cursor:pointer}.error{margin-bottom:18px;border:1px solid #fecaca;border-radius:11px;background:#fff1f2;color:#9f1239;padding:11px 13px}.help{text-align:center;margin-top:20px;color:#64748b;font-size:12px}@media(max-width:850px){body{display:block}.visual{min-height:330px;padding:30px}.visual h1{font-size:42px}.login{min-height:calc(100vh - 330px);padding:22px}.box{padding:28px}}
</style>
</head>
<body>
<section class="visual"><div class="brand"><span class="mark">TM</span> Panel de negocios</div><div><h1>Controla tu comercio desde cualquier lugar.</h1><p>Ventas, pedidos, inventario, clientes y operaciones en un panel diseñado para tu tipo de negocio.</p></div><div class="features"><span>Punto de venta</span><span>Pedidos web</span><span>Inventario</span><span>Analítica</span></div></section>
<main class="login"><form class="box" method="post" action="<?= e($adminBase) ?>/login"><h2>Bienvenido</h2><p>Accede al panel administrativo<?= !empty($storeSlug)?' de este proyecto':'' ?>.</p><?php if($error): ?><div class="error"><?= e($error) ?></div><?php endif; ?><input type="hidden" name="_csrf" value="<?= e(\App\Core\Csrf::token()) ?>"><label class="field">Correo electrónico<input type="email" name="email" value="<?= e($email) ?>" required autocomplete="email" autofocus></label><label class="field">Contraseña<input type="password" name="password" required autocomplete="current-password"></label><button class="submit">Entrar al panel</button><div class="help">Tu acceso es independiente de la consola de soporte.</div></form></main>
</body></html>
